services:
  mysql:
    image: mysql:8.0.25
    container_name: order_db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: order_db
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - order_db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  order_db_data: