services:
  mysql:
    image: mysql:8.0
    container_name: order_db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: order_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql # Persists data even if the container is removed
    restart: unless-stopped # Restarts the container unless it's explicitly stopped

volumes:
  mysql_data: # Defines a named volume for data persistence